### Get users list
GET https://localhost:8000/users?search="hello"
Accept: application/json

### Store user to database
POST http://localhost:8000/users
Content-Type: application/json
Accept: application/json

{
    "name": "name",
    "password": "pass",
    "username": "user"
}

