source = ./general.conf
source = ./input.conf
source = ./binding.conf
source = ./workspace.conf

################
### MONITORS ###
################

monitor=eDP-1,preferred,auto-right,auto
monitor=DP-1,preferred,auto-right,auto
monitor=HDMI-A-1,preferred,auto-left,auto
monitor=,preferred,auto,auto

#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper & firefox & google-chrome-stable & flatpak run org.telegram.desktop -startintray 
exec-once = [workspace 3 silent] ghostty
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = swayosd-server

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

##############################
### WINDOWS AND WORKSPACES ###
##############################

$monitor1 = monitor:DP-1
$monitor2 = monitor:HDMI-A-1

workspace = 1, $monitor1, default:true, persistent:true
workspace = 2, $monitor1, persistent:true, class:^(google-chrome)$
workspace = 3, $monitor1, persistent:true, class:^(com.mitchellh.ghostty)$
workspace = 4, $monitor1, persistent:true, class:^(Postman)$
workspace = 5, $monitor1, persistent:true, class:^(jetbrains-datagrip)$

windowrule = match:class ^(firefox)$, workspace 1
windowrule = match:class ^(org.telegram.desktop)$, workspace 1
windowrule = match:class ^(google-chrome)$, workspace 2
windowrule = match:class ^(Postman)$, workspace 4
windowrule = match:class ^(jetbrains-datagrip)$, workspace 5

workspace = 7, $monitor2
workspace = 8, $monitor2
workspace = 9, $monitor2, default:true

