source = ./general.conf
source = ./input.conf
source = ./binding.conf
source = ./workspace.conf

################
### MONITORS ###
################

#monitor = name, resolution, position, scale, mirror, mirror of

# Laptop monitor PORT
# monitor=eDP-1, preferred, auto, auto
monitorv2 {
    output = eDP-1
    mode = preferred
    position = auto
    scale = auto
    # mirror = HDMI-A-1
}

# PC Desktop PORT
# monitor=DP-1,preferred,auto-right,auto, mirror, HDMI-A-1
monitorv2 {
    output = DP-1
    mode = 1920x1080@143.99
    position = auto-right
    scale = auto
    # mirror = HDMI-A-1
}

monitorv2 {
    output = HDMI-A-1
    mode = preferred
    position = auto-left
    scale = auto
    # mirror = DP-1
}

monitor= , preferred, auto, 1

#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper & google-chrome-stable & Telegram & blueman-applet
# exec-once = [workspace 3 silent] ghostty
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = swayosd-server & swaync

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

##############################
### WINDOWS AND WORKSPACES ###
##############################

$monitor1 = monitor:DP-1
$monitor2 = monitor:HDMI-A-1

workspace = 1, $monitor1, default:true, persistent:true
workspace = 2, $monitor1, persistent:true, class:^(google-chrome)$
workspace = 3, $monitor1, persistent:true, class:^(com.mitchellh.ghostty)$
workspace = 4, $monitor1, persistent:true, class:^(Postman)$
workspace = 5, $monitor1, persistent:true, class:^(jetbrains-datagrip)$

windowrule = match:class ^(org.telegram.desktop)$, workspace 1
windowrule = match:class ^(google-chrome)$, workspace 2
# windowrule = match:class ^(Postman)$, workspace 4
windowrule = match:class ^(jetbrains-datagrip)$, workspace 5


workspace = 7, $monitor2
workspace = 8, $monitor2
workspace = 9, $monitor2, default:true


windowrule = match:class ^(swayimg)$, float on, size 1600 900
windowrule = match:class ^(org.gnome.Nautilus)$, float on, size 1600 900

windowrule = match:class ^(vlc)$, workspace 9
