#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us, kh
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0
    # sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = yes
        disable_while_typing = yes
        tap-to-click = yes
        clickfinger_behavior = yes
        scroll_factor = 0.3
    }

}

# See https://wiki.hypr.land/Configuring/Gestures
# gesture = 4, horizontal, workspace
# gesture = 3, down, mod: ALT, close
# gesture = 4, up, mod: SUPER, fullscreen
# gesture = 3, left, scale: 1.5, float

# Example per-device confi
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
