require("nvim.plugin.nvimtree")
require("nvim.plugin.telescope")
require("nvim.plugin.treesitter")
require("nvim.plugin.lualine")
require("nvim.plugin.indentblank")
require("nvim.plugin.lsp")
require("nvim.plugin.dev")
