CapsLock >> Any
Control{CapsLock} >> CapsLock

AltGr   = AltRight

AltGr{Any} >> Meta{Any}



CapsLock{J} >> ArrowDown
CapsLock{K} >> ArrowUp
CapsLock{H} >> ArrowLeft 
CapsLock{L} >> ArrowRight


CapsLock{P} >> Home 
CapsLock{N} >> End

CapsLock{I} >> Insert

CapsLock{U} >> PageUp
CapsLock{D} >> PageDown
